### ISSUE TITLE
期望未来能集成到webman-admin

### ISSUE THREAD

**Issue by time2045** [shopwwi/webman-filesystem#5]
期望大佬未来能把这个插件集成到官方发布的webman-admin，避免重复造轮子。

**Comment by phcent** [comment]
可以使用呀 你是想让我写组件吧

**Comment by time2045** [comment]
> 可以使用呀 你是想让我写组件吧

直接点，集成在官方的webman-admin源码里，哈哈【手动狗头】

**Comment by phcent** [comment]
> > 可以使用呀 你是想让我写组件吧
> 
> 直接点，集成在官方的webman-admin源码里，哈哈【手动狗头】

这个就无能为力了 除非walker同意

**Comment by time2045** [comment]
> > > 可以使用呀 你是想让我写组件吧
> > 
> > 
> > 直接点，集成在官方的webman-admin源码里，哈哈【手动狗头】
> 
> 这个就无能为力了 除非walker同意
官方鼓励完善代码的，“欢迎pr或者开发成插件发布到平台”
